workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.fluttersample
      vars:
        APP_ID: fecyiw43@gmail.com
      flutter: stable
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

# workflows:
#   android-workflow:
#     name: Android Workflow
#     max_build_duration: 120
#     environment:
#       android_signing:
#         - upload-keystore
#       vars:
#         PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
#         GOOGLE_PLAY_TRACK: "alpha"
#       flutter: stable
#     scripts:
#       - name: Set up local.properties
#         script: | 
#           echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
#       - name: Get Flutter packages
#         script: | 
#           flutter packages pub get
#       - name: Build AAB with Flutter
#         script: | 
#           flutter build appbundle --release
#     artifacts:
#       - build/**/outputs/**/*.aab
#       - build/**/outputs/**/mapping.txt
#       - flutter_drive.log





    # publishing:
    #   email:
    #     recipients:
    #       - user_1@example.com
    #       - user_2@example.com
    #     notify:
    #       success: true
    #       failure: false
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: $GOOGLE_PLAY_TRACK
      #   submit_as_draft: true